const TypesMap = {
  'double': 'number',
  'float': 'number',
  'int32': 'number',
  'int64': 'number',
  'uint32': 'number',
  'uint64': 'number',
  'sint32': 'number',
  'sint64': 'number',
  'fixed32': 'number',
  'fixed64': 'number',
  'sfixed32': 'number',
  'sfixed64': 'number',
  'bool': 'boolean',
  'string': 'string',
  'bytes': 'string',
  'wtypes.Double': 'number',
  'wtypes.Float': 'number',
  'wtypes.Int64': 'number',
  'wtypes.UInt64': 'number',
  'wtypes.Int32': 'number',
  'wtypes.UInt32': 'number',
  'wtypes.Bool': 'boolean',
  'wtypes.String': 'string',
  'wtypes.Time': 'string',
  'wtypes.StringSlice': 'string[]',
  'wtypes.Int64Slice': 'number[]',
  'StringSlice': 'string[]',
  'Int64Slice': 'number[]',
  'null.String': 'string',
  'null.Int64': 'number',
  'null.Int32': 'number'
};

module.exports = TypesMap;
